pipeline {
    agent any
    tools {
        nodejs 'NodeJS'
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/pemadolker/Pemadolker_02230294_DSO101_A1.git'
            }
        }
        stage('Install') {
            steps {
                dir('todo-app/backend') {
                    sh 'npm install'
                }
            }
        }
        stage('Build') {
            steps {
                dir('todo-app/backend') {
                    sh 'npm run build'
                }
            }
        }
        stage('Test') {
            steps {
                dir('todo-app/backend') {
                    sh 'npm test'
                }
            }
            post {
                always {
                    junit 'todo-app/backend/junit.xml'
                }
            }
        }
        stage('Deploy') {
            steps {
                dir('todo-app/backend') {
                    script {
                        docker.build('pdolker/be-todo:latest')
                        docker.withRegistry('https://index.docker.io/v1/', 'docker-hub-creds') {
                            docker.image('pdolker/be-todo:latest').push()
                        }
                    }
                }
            }
        }
    }
    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}