services:
  - type: web
    name: be-todo
    env: docker
    dockerfilePath: ./todo-app/backend/Dockerfile
    rootDir: ./todo-app/backend
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: todo-db
          property: host
      - key: DB_USER
        fromDatabase:
          name: todo-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: todo-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: todo-db
          property: database
      - key: DB_PORT
        fromDatabase:
          name: todo-db
          property: port
      - key: DB_SSL
        value: "true"
      - key: PORT
        value: "5000"

  - type: web
    name: fe-todo
    env: docker
    dockerfilePath: ./todo-app/frontend/Dockerfile
    rootDir: ./todo-app/frontend
    plan: free
    envVars:
      - key: REACT_APP_API_URL
        value: https://be-todo-02230294.onrender.com/

databases:
  - name: todo-db
    plan: free
    databaseName: tododb